.gitignore
=> ignore credentials

.env, .gitignore
=> remove Cognito env vars

createTask/.gitignore, createTask/.vscode/settings.json, createTask/createTask.py, createTask/event.json, createTask/package-lock.json, createTask/package.json, createTask/requirements.txt, createTask/s3util.py, createTask/serverless.yml, createTask/sqsutil.py, createTask/tasktable.py
=> add createTask

updateTask/.gitignore, updateTask/.vscode/settings.json, updateTask/event.json, updateTask/package-lock.json, updateTask/package.json, updateTask/requirements.txt, updateTask/s3util.py, updateTask/serverless.yml, updateTask/sqsutil.py, updateTask/tasktable.py, updateTask/updateTask.py
=> add updateTask

createTask/createTask.py, createTask/event.json, createTask/serverless.yml, createTask/tasktable.py
change createTask for real XVSA
=> change createTask for real XVSA

updateTask/event.json, updateTask/tasktable.py, updateTask/updateTask.py
change updateTask for real XVSA.
=> change updateTask for real XVSA.

frontend/src/task-view.js, frontend/src/task.js, frontend/src/templates.js, task-list-service/handler.js
change frontend and task-list-service for real XVSA.
Add four columns and remove two columns.
=> change frontend, task-list-service for real XVSA

remove.sh
should be remove-task-workflow.sh, and not deploy-task-workflow.sh.
=> fix remove.sh bug

remove-task-workflow.sh
=> fix remove-task-workflow bug

.env, createTask/serverless.yml, processTask/env.sh, resources/serverless.yml, resources/task-list-apps-bucket.yml, resources/task-list-log-data-bucket.yml, resources/task-list-preprocess-data-bucket.yml, resources/task-list-result-data-bucket.yml, submitTask/env.sh, task-list-service/serverless.yml, updateTask/serverless.yml
add TARGET_CLOUD and use in serverless.yml
=> add TARGET_CLOUD and use in serverless.yml

processTask/.dockerignore, submitTask/submitTask.sh
=> add comments to submitTask.sh

submitTask/.gitignore, submitTask/.vscode/settings.json, submitTask/submitTask.sh
print real task config json file name
=> Improve submit task

submitTask/.gitignore
change "submitJob" to "submitTask".
move "submitTask" section to the end.
=> fix typo in submitTask/.gitignore

createTask/.gitignore, createTask/.vscode/settings.json
=> Improve create task

processTask/.gitignore, processTask/.vscode/settings.json
=> Improve process task

processTask/.dockerignore, processTask/.gitignore
move processTask .section to end of .gitignore.
also add IDE section to .dockerignore.
=> move processTask section to end of .gitignore

createTask/.gitignore
move IDE section to above Node and Serverless.
=> move IDE section to above Node and Serverless.

.gitignore, .vscode/settings.json
ignore IDE artifacts and remove vscode related info
=> Remove vscode

updateTask/.gitignore, updateTask/.vscode/settings.json
=> Improve update task

processTask/Dockerfile.mock
create ENGINE_PATH_bin for mock
=> create ENGINE_PATH_bin for mock

remove-task-list.sh, remove-task-workflow.sh, submitTask/submitTask.py
replace references to jobs with task-list or tasks
=> replace references to jobs with task-list or tasks

updateTask/serverless.yml, updateTask/updateTask.py
clean up code that uses task issues queue
=> clean up code that uses task issues queue

uploadTaskIssues/.gitignore, uploadTaskIssues/dotvfile.py, uploadTaskIssues/event.json, uploadTaskIssues/issuetable.py, uploadTaskIssues/package-lock.json, uploadTaskIssues/package.json, uploadTaskIssues/requirements.txt, uploadTaskIssues/s3util.py, uploadTaskIssues/serverless.yml, uploadTaskIssues/sqsutil.py, uploadTaskIssues/uploadTaskIssues.py
uploadTaskIssues initial version
=> uploadTaskIssues initial version

createTask/tasktable.py, updateTask/tasktable.py, uploadTaskIssues/issuetable.py
use deep copy in create_task_record
- use deep copy in create_task_record
- rename "item" to "task_record" or "issue_record" in get functions
=> use deep copy in create_task_record

processTask/bin/xvsa_start.sh
mock xvsa_start.sh should mv and not cp dot v file
=> mock xvsa_start.sh should mv and not cp dot v file

deploy-task-pipeline.sh, remove-task-pipeline.sh, uploadTaskIssues/.gitignore, uploadTaskIssues/csvfile.py, uploadTaskIssues/dotvfile.py, uploadTaskIssues/uploadTaskIssues.py, uploadTaskIssues/writeDotVFileIssuesCSV.py, uploadTaskIssues/xvsa-xfa-dummy.v
decode dot v file issues to task issues.
write task issues to /tmp csv file and issue table.
upload /tmp csv file to result data bucket.
create writeDotVFileIssuesCSV.py to test csvfile.py and dotvfile.py.
=> uploadTaskIssues with CSV file

task-list-frontend/src/task.js, task-list-service/serverless.yml
change current api to v1 api.
change path from "task" to "tasks".
=> change current api to v1 api

generateTaskSummary/src/main/java/com/rwang5688/dal/Issue.java, generateTaskSummary/src/main/java/com/rwang5688/dal/Task.java, task-list-service-v2/serverless.yml, task-list-service-v2/src/main/java/com/rwang5688/DeleteTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/GetTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/GetTaskIssuesHandler.java, task-list-service-v2/src/main/java/com/rwang5688/UpdateTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/dal/Issue.java, task-list-service-v2/src/main/java/com/rwang5688/dal/Task.java
1) Fix Task.get() to query by user_id and task_id.
2) Fix Task API's to query by user_id and task_id in read, update, delete.
3) Remove Issue.list().
=> Fix task.get to query by user id and task

createTask/taskmessage.py, generateTaskSummary/src/main/java/com/rwang5688/GenerateTaskSummaryHandler.java, generateTaskSummary/src/main/java/com/rwang5688/dal/Issue.java, generateTaskSummary/src/main/java/com/rwang5688/dal/Task.java, processTask/taskmessage.py, submitTask/taskmessage.py, task-list-service-v2/pom.xml, task-list-service-v2/src/main/java/com/rwang5688/CreateTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/DeleteTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/GetTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/GetTaskIssuesHandler.java, task-list-service-v2/src/main/java/com/rwang5688/ListTasksHandler.java, task-list-service-v2/src/main/java/com/rwang5688/UpdateTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/dal/Issue.java, task-list-service-v2/src/main/java/com/rwang5688/dal/Task.java, updateTask/taskmessage.py, uploadTaskIssues/taskmessage.py
1) fix send message json in taskmessage.py.
2) consistently use simple logging facade (factory) in all Java classes.
=> Fix send msg json and db access to enable generate task summary

generate-task-summary/src/main/java/com/rwang5688/dal/Task.java, task-list-frontend/src/task-view.js, task-list-frontend/src/task.js, task-list-frontend/src/templates.js, task-list-service-v2/src/main/java/com/rwang5688/CreateTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/UpdateTaskHandler.java, task-list-service-v2/src/main/java/com/rwang5688/dal/Task.java
change to:
task_fileinfo_json
task_preprocess_tar
task_source_code_zip
=> fix task context attributes

update_task/taskurl.py
change get_domain_name to get_base_url
get different 3-region separator and domain name based on cloud
=> refactor get_base_url logic to handle aws + aws-cn

deploy-task-list.sh
=> uncomment the SERVICES list for Java compilation

generate-task-summary/pom.xml, task-list-service-v2/pom.xml
generate-task-summary: add S3 dependency; catch up on AWS SDK for Java v2 dependencies.
task-list-service-v2: add full Lambda dependencies; add Gson dependency; catch up on AWS SDK for Java v2 dependencies.
=> update AWS SDK for Java depedencies

process_task/bin/xvsa_start.sh, process_task/process_task.py
2. process task check scan return code, if scan failed, remove messages from process task queue, update update task queue, upload scan log and setup task status to scan failed
=> 1. when xvsa scan failed, return exit code to process task.

task-list-frontend/package-lock.json, task-list-frontend/package.json
upgrade immer to 8.0.1 per vulnerability fix suggestion.
=> upgrade immer dependencies to fix vulnerability

.env, process_task/env.sh, submit_task/env.sh
remove actual aws account id from repo
=> remove actual aws account id from repo
